name: Deploy via Git

on:
  push:
    branches: 
      - main
    
jobs:
  deploy-via-git:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
      run: |
        echo "Hola caracola"
